name: Build releases


on:
  # you may only define up to 10 `inputs` for a `workflow_dispatch` event
  workflow_dispatch:

jobs:
  pre:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    outputs:
      vdf_sha_short: ${{ steps.set_global_params.outputs.vdf_sha_short }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
          fetch-depth: '0'

      - name: set global params
        id: set_global_params
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/app/src/videoduplicatefinder/
          echo "vdf_sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

  build:
    needs: [pre]
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        kind: ['linux', 'windows', 'linuxarm64']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
            name: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
            name: win-x64
          - kind: linuxarm64
            os: ubuntu-latest
            target: linux-arm64
            name: linux-arm64
            
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
          fetch-depth: '0'

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: change language (Linux)
        if: matrix.kind != 'windows'
        shell: bash
        run: |
          if [ "$(ls -A "$GITHUB_WORKSPACE/replace" 2>/dev/null)" ]; then
            cp -rf "$GITHUB_WORKSPACE/replace/"* "$GITHUB_WORKSPACE/app/src/videoduplicatefinder/"
          fi

      - name: change language (Windows)
        if: matrix.kind == 'windows'
        shell: powershell
        run: |
          if ((Get-ChildItem "$env:GITHUB_WORKSPACE\replace" -ErrorAction SilentlyContinue).Count -gt 0) {
            Copy-Item "$env:GITHUB_WORKSPACE\replace\*" "$env:GITHUB_WORKSPACE\app\src\videoduplicatefinder" -Recurse -Force
          }

      - name: build and zip
        shell: bash
        run: |
            cd $GITHUB_WORKSPACE/app/src/videoduplicatefinder/
            release_name="App-${{ matrix.target }}-3.0.${{ needs.pre.outputs.vdf_sha_short }}"
            # Add nuget sources
            dotnet nuget add source https://www.myget.org/F/sixlabors/api/v3/index.json
            # Build everything
            dotnet publish ./VDF.GUI/VDF.GUI.csproj -c Release -v q --self-contained -r "${{ matrix.target }}" -o "outputFolder"
            # Pack files
            if [ "${{ matrix.target }}" == "win-x64" ]; then
              # Pack to zip for Windows
              7z a -tzip "${release_name}.zip" "./outputFolder/*"
            else
              tar czvf "${release_name}.tar.gz" "outputFolder"
            fi
            # Delete output directory
            rm -r "outputFolder"

      - name: Upload zips
        uses: actions/upload-artifact@v6
        with:
          name: bin-App-${{ matrix.target }}-3.0.${{ needs.pre.outputs.vdf_sha_short }}
          compression-level: 9
          path: |
            ${{ github.workspace }}/app/src/videoduplicatefinder/App-*

  release:
    needs: [pre, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Download zips archives
        uses: actions/download-artifact@v7
        with:
          pattern: "bin*"
          merge-multiple: true
          path: ${{ github.workspace }}/archives

      - name: show zips files
        run: |
          tree ${{ github.workspace }}/archives

      - name: Release archives
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "3.0.${{ needs.pre.outputs.vdf_sha_short }}"
          name: "3.0.${{ needs.pre.outputs.vdf_sha_short }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          body: |
            [Last build based on ${{ needs.pre.outputs.vdf_sha_short }}]
            Note: 
            [Attachments are automatically created and replaced on every new commit.]
            Regardless of what the message above says. 
            If you experience upgrade issues you may need to delete your 'ScannedFiles.db' file in VDF folder.
          files: |
            ${{ github.workspace }}/archives/**
